// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// PrimaryAccountSmartSwitchRestoreService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PrimaryAccountSmartSwitchRestoreService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath =
		"/ext/auth/feature-guest/thrift/account/v1/restore/smart-switch";
	errorName = "PrimaryAccountSmartSwitchRestoreServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async checkEmailAssigned(
		...param: Parameters<typeof LINEStruct.checkEmailAssigned_args>
	): Promise<LINETypes.checkEmailAssigned_result["success"]> {
		return await this.client.request.request(
			LINEStruct.checkEmailAssigned_args(...param),
			"checkEmailAssigned",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async checkIfPasswordSetVerificationEmailVerified(
		...param: Parameters<
			typeof LINEStruct.checkIfPasswordSetVerificationEmailVerified_args
		>
	): Promise<
		LINETypes.checkIfPasswordSetVerificationEmailVerified_result["success"]
	> {
		return await this.client.request.request(
			LINEStruct.checkIfPasswordSetVerificationEmailVerified_args(...param),
			"checkIfPasswordSetVerificationEmailVerified",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getAcctVerifMethod(
		...param: Parameters<typeof LINEStruct.getAcctVerifMethod_args>
	): Promise<LINETypes.getAcctVerifMethod_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getAcctVerifMethod_args(...param),
			"getAcctVerifMethod",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCountryInfo(
		...param: Parameters<typeof LINEStruct.getCountryInfo_args>
	): Promise<LINETypes.getCountryInfo_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCountryInfo_args(...param),
			"getCountryInfo",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getMaskedEmail(
		...param: Parameters<typeof LINEStruct.getMaskedEmail_args>
	): Promise<LINETypes.getMaskedEmail_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getMaskedEmail_args(...param),
			"getMaskedEmail",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPasswordHashingParametersForPwdReg(
		...param: Parameters<
			typeof LINEStruct.getPasswordHashingParametersForPwdReg_args
		>
	): Promise<
		LINETypes.getPasswordHashingParametersForPwdReg_result["success"]
	> {
		return await this.client.request.request(
			LINEStruct.getPasswordHashingParametersForPwdReg_args(...param),
			"getPasswordHashingParametersForPwdReg",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPasswordHashingParametersForPwdVerif(
		...param: Parameters<
			typeof LINEStruct.getPasswordHashingParametersForPwdVerif_args
		>
	): Promise<
		LINETypes.getPasswordHashingParametersForPwdVerif_result["success"]
	> {
		return await this.client.request.request(
			LINEStruct.getPasswordHashingParametersForPwdVerif_args(...param),
			"getPasswordHashingParametersForPwdVerif",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPhoneVerifMethodV2(
		...param: Parameters<typeof LINEStruct.getPhoneVerifMethodV2_args>
	): Promise<LINETypes.getPhoneVerifMethodV2_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPhoneVerifMethodV2_args(...param),
			"getPhoneVerifMethodV2",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async requestToSendPasswordSetVerificationEmail(
		...param: Parameters<
			typeof LINEStruct.requestToSendPasswordSetVerificationEmail_args
		>
	): Promise<
		LINETypes.requestToSendPasswordSetVerificationEmail_result["success"]
	> {
		return await this.client.request.request(
			LINEStruct.requestToSendPasswordSetVerificationEmail_args(...param),
			"requestToSendPasswordSetVerificationEmail",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async requestToSendPhonePinCode(
		...param: Parameters<typeof LINEStruct.requestToSendPhonePinCode_args>
	): Promise<LINETypes.requestToSendPhonePinCode_result["success"]> {
		return await this.client.request.request(
			LINEStruct.requestToSendPhonePinCode_args(...param),
			"requestToSendPhonePinCode",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async setHashedPassword(
		...param: Parameters<typeof LINEStruct.setHashedPassword_args>
	): Promise<LINETypes.setHashedPassword_result["success"]> {
		return await this.client.request.request(
			LINEStruct.setHashedPassword_args(...param),
			"setHashedPassword",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyAccountUsingHashedPwd(
		...param: Parameters<typeof LINEStruct.verifyAccountUsingHashedPwd_args>
	): Promise<LINETypes.verifyAccountUsingHashedPwd_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyAccountUsingHashedPwd_args(...param),
			"verifyAccountUsingHashedPwd",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyEapLogin(
		...param: Parameters<typeof LINEStruct.verifyEapLogin_args>
	): Promise<LINETypes.verifyEapLogin_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyEapLogin_args(...param),
			"verifyEapLogin",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyPhonePinCode(
		...param: Parameters<typeof LINEStruct.verifyPhonePinCode_args>
	): Promise<LINETypes.verifyPhonePinCode_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyPhonePinCode_args(...param),
			"verifyPhonePinCode",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
