// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// PwlessPrimaryRegistrationService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PwlessPrimaryRegistrationService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/ACCT/authfactor/pwless/v1";
	errorName = "PwlessPrimaryRegistrationServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async createSession(
		...param: Parameters<typeof LINEStruct.createSession_args>
	): Promise<LINETypes.createSession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createSession_args(...param),
			"createSession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getChallengeForPrimaryReg(
		...param: Parameters<typeof LINEStruct.getChallengeForPrimaryReg_args>
	): Promise<LINETypes.getChallengeForPrimaryReg_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getChallengeForPrimaryReg_args(...param),
			"getChallengeForPrimaryReg",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
