// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PwlessPrimaryRegistrationService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/ACCT/authfactor/pwless/v1";
	errorName = "PwlessPrimaryRegistrationServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async createSession(
		...param: Parameters<typeof LINEStruct.createSession_args>
	): Promise<LINETypes.createSession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createSession_args(...param),
			"createSession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getChallengeForPrimaryReg(
		...param: Parameters<typeof LINEStruct.getChallengeForPrimaryReg_args>
	): Promise<LINETypes.getChallengeForPrimaryReg_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getChallengeForPrimaryReg_args(...param),
			"getChallengeForPrimaryReg",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
