// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class AccountAuthFactorEapConnectService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/ACCT/authfactor/eap/v1";
	errorName = "AccountAuthFactorEapConnectServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async connectEapAccount(
		...param: Parameters<typeof LINEStruct.connectEapAccount_args>
	): Promise<LINETypes.connectEapAccount_result["success"]> {
		return await this.client.request.request(
			LINEStruct.connectEapAccount_args(...param),
			"connectEapAccount",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async disconnectEapAccount(
		...param: Parameters<typeof LINEStruct.disconnectEapAccount_args>
	): Promise<LINETypes.disconnectEapAccount_result["success"]> {
		return await this.client.request.request(
			LINEStruct.disconnectEapAccount_args(...param),
			"disconnectEapAccount",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async openSession(
		...param: Parameters<typeof LINEStruct.openSession_args>
	): Promise<LINETypes.openSession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.openSession_args(...param),
			"openSession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyEapLogin(
		...param: Parameters<typeof LINEStruct.verifyEapLogin_args>
	): Promise<LINETypes.verifyEapLogin_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyEapLogin_args(...param),
			"verifyEapLogin",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
