// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PrimaryQrCodeMigrationLongPollingService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/auth/feature-user/lp/api/primary/mig/qr";
	errorName = "PrimaryQrCodeMigrationLongPollingServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async checkIfEncryptedE2EEKeyReceived(
		...param: Parameters<typeof LINEStruct.checkIfEncryptedE2EEKeyReceived_args>
	): Promise<LINETypes.checkIfEncryptedE2EEKeyReceived_result["success"]> {
		return await this.client.request.request(
			LINEStruct.checkIfEncryptedE2EEKeyReceived_args(...param),
			"checkIfEncryptedE2EEKeyReceived",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
