// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class OaChatService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/ext/oachat/api/";
	errorName = "OaChatServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getCallStatus(
		...param: Parameters<typeof LINEStruct.getCallStatus_args>
	): Promise<LINETypes.getCallStatus_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCallStatus_args(...param),
			"getCallStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
