// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// OaChatService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class OaChatService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/ext/oachat/api/";
	errorName = "OaChatServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getCallStatus(
		...param: Parameters<typeof LINEStruct.getCallStatus_args>
	): Promise<LINETypes.getCallStatus_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCallStatus_args(...param),
			"getCallStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
