// LINE PLANET / Cassini call signaling, reverse-engineered from a
// real tom-call's `pln_msg_pack` + `ear_crypto_hkdf` Frida capture.
// See docs/PLANET_PROTOCOL.md for the full reverse-engineering trail.

export {
	buildFrameHeader,
	makeChunkHdr,
	makeFixedHdr,
	parseChunkHdr,
	parseFixedHdr,
	parseFrameHeader,
	type PlanetFixedHdr,
} from "./framing.ts";

export {
	aesCtrDecrypt,
	aesCtrEncrypt,
	buildCtrIv,
	buildDirectionLabel,
	buildPlanetCtrIv,
	buildPlanetMediaKeyInfo,
	decodeMpKey,
	decodeStnpkPublicKey,
	deriveCallKeys,
	derivePlanetMediaKeys,
	ecdh,
	type EphemeralKeypair,
	generateEphemeralKeypair,
	hmacTag,
	newSessionId,
	planetHkdfStage1,
	planetHkdfStage2,
	planetKdfSha256,
	planetKdfSha512,
	type PlanetMediaKeyLocal,
	type PlanetMediaKeyPeer,
	type PlanetMediaKeys,
	sha256,
	tagEquals,
	type TransportKeys,
} from "./crypto.ts";

export {
	buildExchangeAppStrData,
	buildRelReq,
	buildSetupReq,
	type CassiniBody,
	type CassiniEnvelope,
	type CassiniHeader,
	decodePb,
	decodeVarint,
	encodePb,
	encodeVarint,
	packCassini,
	packCassiniBody,
	packCassiniHeader,
	type PbField,
	unpackCassini,
	unpackCassiniBody,
	WireType,
} from "./cassini.ts";

export {
	type PlanetAnswerResult,
	type PlanetIncomingMessage,
	type PlanetInviteResult,
	type PlanetLocalMediaOffer,
	PlanetTransport,
	type PlanetTransportOpts,
} from "./transport.ts";

// Ground-truth Cassini protobuf-c schema (reverse-engineered from the
// .data.rel.ro descriptor objects in libandromeda).
export {
	CC_MSG,
	CC_MSG_NAMES,
	type CcConnReq,
	type CcConnRsp,
	type CcSetupReq,
	type CcSetupRsp,
	decodeCcConnReq,
	decodeCcConnRsp,
	decodeCcSetupRsp,
	type DecodedField,
	type DecodedPlanetCcHdr,
	type DecodedPlanetCcMsg,
	type DecodedPlanetMsg,
	type DecodedPlanetMsgHdr,
	decodeFields,
	decodeNativeSetupOffer,
	decodePlanetAddr,
	decodePlanetCcMsg,
	decodePlanetMsg,
	decodePlanetMsgHdr,
	extractRmtNonceFromReply,
	type NativeSetupMediaRecord,
	type NativeSetupOffer,
	packCcConnReq,
	packCcConnRsp,
	packCcRelReq,
	packCcSetupReq,
	packKeepaliveReq,
	packNativeSetupOffer,
	packPlanetAddr,
	packPlanetCcHdr,
	packPlanetCcMsg,
	packPlanetFeatureRegister,
	packPlanetMsg,
	packPlanetMsgHdr,
	packPlanetScMsgKaReq,
	packPlanetUserAgent,
	type PlanetAddr,
	type PlanetCcHdr,
	type PlanetMsgBody,
	type PlanetMsgHdr,
	type PlanetSetupOfferMaterial,
	type PlanetUserAgent,
	wrapCcMsg,
} from "./schema.ts";
