// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// AccessTokenRefreshService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class AccessTokenRefreshService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/auth/tokenrefresh/v1";
	errorName = "AccessTokenRefreshServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async refresh(
		...param: Parameters<typeof LINEStruct.refresh_args>
	): Promise<LINETypes.refresh_result["success"]> {
		return await this.client.request.request(
			LINEStruct.refresh_args(...param),
			"refresh",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async reportRefreshedAccessToken(
		...param: Parameters<typeof LINEStruct.reportRefreshedAccessToken_args>
	): Promise<LINETypes.reportRefreshedAccessToken_result["success"]> {
		return await this.client.request.request(
			LINEStruct.reportRefreshedAccessToken_args(...param),
			"reportRefreshedAccessToken",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
