// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class OaMembershipService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/bot/oafan";
	errorName = "OaMembershipServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async activateSubscription(
		...param: Parameters<typeof LINEStruct.activateSubscription_args>
	): Promise<void> {
		return await this.client.request.request(
			LINEStruct.activateSubscription_args(...param),
			"activateSubscription",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getJoinedMembership(
		...param: Parameters<typeof LINEStruct.getJoinedMembership_args>
	): Promise<LINETypes.getJoinedMembership_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getJoinedMembership_args(...param),
			"getJoinedMembership",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
