/**
 * @description Generate linejs service modules from `endpoints.json`.
 *
 * `endpoints.json` is linejs's own service-catalog manifest — a map from
 * `ServiceName` (e.g. `TalkService`, `ShopService`) to `{ endpoint,
 * protocolType, methods? }`. It is the canonical source of truth for
 * which RPC endpoints a service exposes, and replaces an earlier
 * dependency on CHRLINE-Patch's Python service files. The
 * `discover_services_from_apk.ts` script can suggest additions by
 * walking a decompiled smali tree, but humans hold the merge bit.
 *
 * For each service in the manifest the generator emits a TypeScript
 * wrapper at `packages/linejs/base/service/<short>/mod.ts` where each
 * method routes through `client.request.request`. A method is included
 * only when `<method>_args` and `<method>_result` exist in linejs's
 * Thrift schema (`packages/types/thrift.ts`), so the generated code
 * type-checks against the published types package.
 *
 * Manifest entries with an explicit `"methods": [...]` list emit only
 * those methods. Entries without `methods` emit every RPC the Thrift
 * schema has whose `<m>_args` exists — useful when adding a new service
 * to let the schema's coverage define the surface.
 *
 * Hand-written services in the SKIP_LIST below are not overwritten — re-
 * running the generator is safe.
 *
 * Usage:
 *   deno run -A scripts/services/gen_services.ts [--apply]
 *                                                 [--service <Name>]
 *                                                 [--manifest <path>]
 */
import { fromFileUrl, resolve as pathResolve } from "https://deno.land/std@0.224.0/path/mod.ts";

interface Args {
	apply: boolean;
	manifest: string;
	serviceFilter: Set<string> | null;
}

function parseArgs(argv: string[]): Args {
	const out: Args = { apply: false, manifest: "", serviceFilter: null };
	const filter = new Set<string>();
	for (let i = 0; i < argv.length; i++) {
		const a = argv[i];
		switch (a) {
			case "--apply":
				out.apply = true;
				break;
			case "--manifest":
				out.manifest = argv[++i];
				break;
			case "--service":
				filter.add(argv[++i]);
				break;
			default:
				throw new Error(`unknown arg: ${a}`);
		}
	}
	if (filter.size > 0) out.serviceFilter = filter;
	return out;
}

interface EndpointEntry {
	endpoint: string;
	protocolType: number;
	/** Optional whitelist of method names to emit. If absent, emits every
	 *  RPC whose `<m>_args` exists in the Thrift schema. */
	methods?: string[];
}
type EndpointManifest = Record<string, EndpointEntry>;

/** Services owned by hand-written modules. Re-running the generator
 *  never overwrites these — their behaviour is non-trivial (custom
 *  error handling, batched send, etc.) and the generated template
 *  would lose detail. */
const SKIP_LIST = new Set([
	"AuthService",
	"CallService",
	"ChannelService",
	"LiffService",
	"RelationService",
	"SquareLiveTalkService",
	"SquareService",
	"TalkService",
]);

function shortDirName(serviceClassName: string): string {
	return serviceClassName.replace(/Service$/, "").toLowerCase();
}

interface FieldRec { fid: number }

function hasSuccessField(method: string, thrift: Record<string, unknown>): boolean {
	const entry = thrift[`${method}_result`];
	if (!Array.isArray(entry)) return false;
	return (entry as FieldRec[]).some((f) => f.fid === 0);
}

function emitModule(
	serviceClassName: string,
	entry: EndpointEntry,
	thrift: Record<string, unknown>,
	knownMethods: Set<string>,
): { content: string; included: string[]; skipped: string[] } {
	const candidates = entry.methods ?? [...knownMethods];
	const included: string[] = [];
	const skipped: string[] = [];
	for (const m of candidates) {
		if (knownMethods.has(m)) included.push(m);
		else skipped.push(m);
	}

	const methodBodies = included.map((name) => {
		const ret = hasSuccessField(name, thrift)
			? `LINETypes.${name}_result["success"]`
			: "void";
		return `	async ${name}(
		...param: Parameters<typeof LINEStruct.${name}_args>
	): Promise<${ret}> {
		return await this.client.request.request(
			LINEStruct.${name}_args(...param),
			"${name}",
			this.protocolType,
			true,
			this.requestPath,
		);
	}`;
	}).join("\n\n");

	const content = `// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class ${serviceClassName} implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = ${entry.protocolType};
	requestPath = "${entry.endpoint}";
	errorName = "${serviceClassName}Error";
	constructor(client: BaseClient) {
		this.client = client;
	}

${methodBodies}
}
`;
	return { content, included, skipped };
}

async function loadThrift(linejsRoot: string): Promise<Record<string, unknown>> {
	const thriftPath = `${linejsRoot}/packages/types/thrift.ts`;
	const mod = await import(`file://${thriftPath.replaceAll("\\", "/")}`);
	return mod.Thrift as Record<string, unknown>;
}

async function findLinejsRoot(): Promise<string> {
	const here = pathResolve(fromFileUrl(import.meta.url), "..");
	let cur = here;
	while (true) {
		try {
			await Deno.stat(`${cur}/packages/linejs/deno.json`);
			return cur;
		} catch {
			const parent = pathResolve(cur, "..");
			if (parent === cur) throw new Error("could not locate linejs root");
			cur = parent;
		}
	}
}

async function main() {
	const args = parseArgs(Deno.args);
	const linejsRoot = await findLinejsRoot();
	const manifestPath = args.manifest
		? pathResolve(args.manifest)
		: `${linejsRoot}/scripts/services/endpoints.json`;
	const outRoot = `${linejsRoot}/packages/linejs/base/service`;

	console.log(`linejs root: ${linejsRoot}`);
	console.log(`manifest:    ${manifestPath}`);

	const manifest = JSON.parse(
		await Deno.readTextFile(manifestPath),
	) as EndpointManifest;
	const thrift = await loadThrift(linejsRoot);

	const knownMethods = new Set<string>();
	for (const k of Object.keys(thrift)) {
		const m = /^([a-z]\w*)_args$/.exec(k);
		if (m && Array.isArray(thrift[`${m[1]}_result`])) knownMethods.add(m[1]);
	}
	console.log(`linejs Thrift schema has ${knownMethods.size} method args/result pairs`);

	let totalIncluded = 0;
	let totalSkipped = 0;
	let touched = 0;
	for (const [serviceClassName, entry] of Object.entries(manifest)) {
		if (SKIP_LIST.has(serviceClassName)) {
			continue;
		}
		if (
			args.serviceFilter &&
			!args.serviceFilter.has(serviceClassName) &&
			!args.serviceFilter.has(serviceClassName.replace(/Service$/, ""))
		) continue;
		const { content, included, skipped } = emitModule(
			serviceClassName,
			entry,
			thrift,
			knownMethods,
		);
		if (included.length === 0) {
			console.log(`  ${serviceClassName}: no methods present in Thrift — skipping`);
			continue;
		}
		const dir = `${outRoot}/${shortDirName(serviceClassName)}`;
		const file = `${dir}/mod.ts`;
		console.log(
			`  ${serviceClassName} (${entry.endpoint}, type=${entry.protocolType}): ` +
				`${included.length} method(s)` +
				(skipped.length > 0 ? `, ${skipped.length} skipped` : ""),
		);
		totalIncluded += included.length;
		totalSkipped += skipped.length;
		if (args.apply) {
			await Deno.mkdir(dir, { recursive: true });
			await Deno.writeTextFile(file, content);
			touched++;
		}
	}

	console.log();
	console.log(
		`summary: ${totalIncluded} methods across ${touched || Object.keys(manifest).length - SKIP_LIST.size} services, ${totalSkipped} skipped`,
	);
	if (!args.apply) console.log("(dry-run; pass --apply to write modules)");
}

if (import.meta.main) {
	await main();
}
