// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// BotExternalService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class BotExternalService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/BOTE";
	errorName = "BotExternalServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async notifyOATalkroomEvents(
		...param: Parameters<typeof LINEStruct.notifyOATalkroomEvents_args>
	): Promise<LINETypes.notifyOATalkroomEvents_result["success"]> {
		return await this.client.request.request(
			LINEStruct.notifyOATalkroomEvents_args(...param),
			"notifyOATalkroomEvents",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async notifyChatAdEntry(
		...param: Parameters<typeof LINEStruct.notifyChatAdEntry_args>
	): Promise<LINETypes.notifyChatAdEntry_result["success"]> {
		return await this.client.request.request(
			LINEStruct.notifyChatAdEntry_args(...param),
			"notifyChatAdEntry",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
