// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// PremiumStatusService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PremiumStatusService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/line-premium/common/thrift/status";
	errorName = "PremiumStatusServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getPremiumStatus(
		...param: Parameters<typeof LINEStruct.getPremiumStatus_args>
	): Promise<LINETypes.getPremiumStatus_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPremiumStatus_args(...param),
			"getPremiumStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPremiumStatusForUpgrade(
		...param: Parameters<typeof LINEStruct.getPremiumStatusForUpgrade_args>
	): Promise<LINETypes.getPremiumStatusForUpgrade_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPremiumStatusForUpgrade_args(...param),
			"getPremiumStatusForUpgrade",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getDataRetention(
		...param: Parameters<typeof LINEStruct.getDataRetention_args>
	): Promise<LINETypes.getDataRetention_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getDataRetention_args(...param),
			"getDataRetention",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getIncentiveStatus(
		...param: Parameters<typeof LINEStruct.getIncentiveStatus_args>
	): Promise<LINETypes.getIncentiveStatus_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getIncentiveStatus_args(...param),
			"getIncentiveStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
