// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class BuddyService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/BUDDY4";
	errorName = "BuddyServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getPromotedBuddyContacts(
		...param: Parameters<typeof LINEStruct.getPromotedBuddyContacts_args>
	): Promise<LINETypes.getPromotedBuddyContacts_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPromotedBuddyContacts_args(...param),
			"getPromotedBuddyContacts",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getBuddyDetailWithPersonal(
		...param: Parameters<typeof LINEStruct.getBuddyDetailWithPersonal_args>
	): Promise<LINETypes.getBuddyDetailWithPersonal_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getBuddyDetailWithPersonal_args(...param),
			"getBuddyDetailWithPersonal",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getNewlyReleasedBuddyIds(
		...param: Parameters<typeof LINEStruct.getNewlyReleasedBuddyIds_args>
	): Promise<LINETypes.getNewlyReleasedBuddyIds_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getNewlyReleasedBuddyIds_args(...param),
			"getNewlyReleasedBuddyIds",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getBuddyDetail(
		...param: Parameters<typeof LINEStruct.getBuddyDetail_args>
	): Promise<LINETypes.getBuddyDetail_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getBuddyDetail_args(...param),
			"getBuddyDetail",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
