// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// HomeSafetyCheckService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class HomeSafetyCheckService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/home/safety-check/safety-check";
	errorName = "HomeSafetyCheckServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async deleteSafetyStatus(
		...param: Parameters<typeof LINEStruct.deleteSafetyStatus_args>
	): Promise<void> {
		return await this.client.request.request(
			LINEStruct.deleteSafetyStatus_args(...param),
			"deleteSafetyStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getDisasterCases(
		...param: Parameters<typeof LINEStruct.getDisasterCases_args>
	): Promise<LINETypes.getDisasterCases_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getDisasterCases_args(...param),
			"getDisasterCases",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async updateSafetyStatus(
		...param: Parameters<typeof LINEStruct.updateSafetyStatus_args>
	): Promise<void> {
		return await this.client.request.request(
			LINEStruct.updateSafetyStatus_args(...param),
			"updateSafetyStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
