// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// SettingsService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class SettingsService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/US4";
	errorName = "SettingsServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async bulkGetSetting(
		...param: Parameters<typeof LINEStruct.bulkGetSetting_args>
	): Promise<LINETypes.bulkGetSetting_result["success"]> {
		return await this.client.request.request(
			LINEStruct.bulkGetSetting_args(...param),
			"bulkGetSetting",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async bulkSetSetting(
		...param: Parameters<typeof LINEStruct.bulkSetSetting_args>
	): Promise<LINETypes.bulkSetSetting_result["success"]> {
		return await this.client.request.request(
			LINEStruct.bulkSetSetting_args(...param),
			"bulkSetSetting",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
