// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class SettingsService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/US4";
	errorName = "SettingsServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async bulkGetSetting(
		...param: Parameters<typeof LINEStruct.bulkGetSetting_args>
	): Promise<LINETypes.bulkGetSetting_result["success"]> {
		return await this.client.request.request(
			LINEStruct.bulkGetSetting_args(...param),
			"bulkGetSetting",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async bulkSetSetting(
		...param: Parameters<typeof LINEStruct.bulkSetSetting_args>
	): Promise<LINETypes.bulkSetSetting_result["success"]> {
		return await this.client.request.request(
			LINEStruct.bulkSetSetting_args(...param),
			"bulkSetSetting",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
