// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// DeviceAttestationService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class DeviceAttestationService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/auth/feature-user/api/primary/device-attestation";
	errorName = "DeviceAttestationServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getAssertionChallenge(
		...param: Parameters<typeof LINEStruct.getAssertionChallenge_args>
	): Promise<LINETypes.getAssertionChallenge_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getAssertionChallenge_args(...param),
			"getAssertionChallenge",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getAttestationChallenge(
		...param: Parameters<typeof LINEStruct.getAttestationChallenge_args>
	): Promise<LINETypes.getAttestationChallenge_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getAttestationChallenge_args(...param),
			"getAttestationChallenge",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyAssertion(
		...param: Parameters<typeof LINEStruct.verifyAssertion_args>
	): Promise<LINETypes.verifyAssertion_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyAssertion_args(...param),
			"verifyAssertion",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyAttestation(
		...param: Parameters<typeof LINEStruct.verifyAttestation_args>
	): Promise<LINETypes.verifyAttestation_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyAttestation_args(...param),
			"verifyAttestation",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
