// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// ShopAuthService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class ShopAuthService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/SHOPA";
	errorName = "ShopAuthServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async establishE2EESession(
		...param: Parameters<typeof LINEStruct.establishE2EESession_args>
	): Promise<LINETypes.establishE2EESession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.establishE2EESession_args(...param),
			"establishE2EESession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
