// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// SquareBotService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class SquareBotService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/BP1";
	errorName = "SquareBotServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getSquareBot(
		...param: Parameters<typeof LINEStruct.getSquareBot_args>
	): Promise<LINETypes.getSquareBot_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getSquareBot_args(...param),
			"getSquareBot",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
