// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// PrimaryQrCodeMigrationPreparationService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PrimaryQrCodeMigrationPreparationService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/auth/feature-user/api/primary/mig/qr/prepare";
	errorName = "PrimaryQrCodeMigrationPreparationServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async createSession(
		...param: Parameters<typeof LINEStruct.createSession_args>
	): Promise<LINETypes.createSession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createSession_args(...param),
			"createSession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async sendEncryptedE2EEKey(
		...param: Parameters<typeof LINEStruct.sendEncryptedE2EEKey_args>
	): Promise<LINETypes.sendEncryptedE2EEKey_result["success"]> {
		return await this.client.request.request(
			LINEStruct.sendEncryptedE2EEKey_args(...param),
			"sendEncryptedE2EEKey",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
