// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// PasswordUpdateService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PasswordUpdateService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/auth/feature-user/api/primary/password/update";
	errorName = "PasswordUpdateServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async createSession(
		...param: Parameters<typeof LINEStruct.createSession_args>
	): Promise<LINETypes.createSession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createSession_args(...param),
			"createSession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPasswordHashingParameter(
		...param: Parameters<typeof LINEStruct.getPasswordHashingParameter_args>
	): Promise<LINETypes.getPasswordHashingParameter_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPasswordHashingParameter_args(...param),
			"getPasswordHashingParameter",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async setPassword(
		...param: Parameters<typeof LINEStruct.setPassword_args>
	): Promise<LINETypes.setPassword_result["success"]> {
		return await this.client.request.request(
			LINEStruct.setPassword_args(...param),
			"setPassword",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async updatePassword(
		...param: Parameters<typeof LINEStruct.updatePassword_args>
	): Promise<LINETypes.updatePassword_result["success"]> {
		return await this.client.request.request(
			LINEStruct.updatePassword_args(...param),
			"updatePassword",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
