// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// PremiumFontService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PremiumFontService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EXT/talk/asset-meta-server/thrift/fontService";
	errorName = "PremiumFontServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getAccessToken(
		...param: Parameters<typeof LINEStruct.getAccessToken_args>
	): Promise<LINETypes.getAccessToken_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getAccessToken_args(...param),
			"getAccessToken",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getFontMetas(
		...param: Parameters<typeof LINEStruct.getFontMetas_args>
	): Promise<LINETypes.getFontMetas_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getFontMetas_args(...param),
			"getFontMetas",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
