// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// MultiProfileService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class MultiProfileService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/PFS4";
	errorName = "MultiProfileServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async deleteMultiProfile(
		...param: Parameters<typeof LINEStruct.deleteMultiProfile_args>
	): Promise<LINETypes.deleteMultiProfile_result["success"]> {
		return await this.client.request.request(
			LINEStruct.deleteMultiProfile_args(...param),
			"deleteMultiProfile",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getMappedProfileIds(
		...param: Parameters<typeof LINEStruct.getMappedProfileIds_args>
	): Promise<LINETypes.getMappedProfileIds_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getMappedProfileIds_args(...param),
			"getMappedProfileIds",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async mapProfileToUsers(
		...param: Parameters<typeof LINEStruct.mapProfileToUsers_args>
	): Promise<LINETypes.mapProfileToUsers_result["success"]> {
		return await this.client.request.request(
			LINEStruct.mapProfileToUsers_args(...param),
			"mapProfileToUsers",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async updateProfileAttributes(
		...param: Parameters<typeof LINEStruct.updateProfileAttributes_args>
	): Promise<void> {
		return await this.client.request.request(
			LINEStruct.updateProfileAttributes_args(...param),
			"updateProfileAttributes",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async createMultiProfile(
		...param: Parameters<typeof LINEStruct.createMultiProfile_args>
	): Promise<LINETypes.createMultiProfile_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createMultiProfile_args(...param),
			"createMultiProfile",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getProfile(
		...param: Parameters<typeof LINEStruct.getProfile_args>
	): Promise<LINETypes.getProfile_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getProfile_args(...param),
			"getProfile",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getUsersMappedByProfile(
		...param: Parameters<typeof LINEStruct.getUsersMappedByProfile_args>
	): Promise<LINETypes.getUsersMappedByProfile_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getUsersMappedByProfile_args(...param),
			"getUsersMappedByProfile",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
