// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class E2EEKeyBackupService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/EKBS4";
	errorName = "E2EEKeyBackupServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getE2EEKeyBackupCertificates(
		...param: Parameters<typeof LINEStruct.getE2EEKeyBackupCertificates_args>
	): Promise<LINETypes.getE2EEKeyBackupCertificates_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getE2EEKeyBackupCertificates_args(...param),
			"getE2EEKeyBackupCertificates",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getE2EEKeyBackupInfo(
		...param: Parameters<typeof LINEStruct.getE2EEKeyBackupInfo_args>
	): Promise<LINETypes.getE2EEKeyBackupInfo_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getE2EEKeyBackupInfo_args(...param),
			"getE2EEKeyBackupInfo",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
