// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class PrimaryAccountReLoginService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/ext/auth/feature-guest/thrift/account/v1/relogin/primary";
	errorName = "PrimaryAccountReLoginServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async createSession(
		...param: Parameters<typeof LINEStruct.createSession_args>
	): Promise<LINETypes.createSession_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createSession_args(...param),
			"createSession",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCountryInfo(
		...param: Parameters<typeof LINEStruct.getCountryInfo_args>
	): Promise<LINETypes.getCountryInfo_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCountryInfo_args(...param),
			"getCountryInfo",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPhoneVerifMethodV2(
		...param: Parameters<typeof LINEStruct.getPhoneVerifMethodV2_args>
	): Promise<LINETypes.getPhoneVerifMethodV2_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPhoneVerifMethodV2_args(...param),
			"getPhoneVerifMethodV2",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async requestToSendPhonePinCode(
		...param: Parameters<typeof LINEStruct.requestToSendPhonePinCode_args>
	): Promise<LINETypes.requestToSendPhonePinCode_result["success"]> {
		return await this.client.request.request(
			LINEStruct.requestToSendPhonePinCode_args(...param),
			"requestToSendPhonePinCode",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyEapLogin(
		...param: Parameters<typeof LINEStruct.verifyEapLogin_args>
	): Promise<LINETypes.verifyEapLogin_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyEapLogin_args(...param),
			"verifyEapLogin",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async verifyPhonePinCode(
		...param: Parameters<typeof LINEStruct.verifyPhonePinCode_args>
	): Promise<LINETypes.verifyPhonePinCode_result["success"]> {
		return await this.client.request.request(
			LINEStruct.verifyPhonePinCode_args(...param),
			"verifyPhonePinCode",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
