// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class CoinService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/COIN4";
	errorName = "CoinServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getTotalCoinBalance(
		...param: Parameters<typeof LINEStruct.getTotalCoinBalance_args>
	): Promise<LINETypes.getTotalCoinBalance_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getTotalCoinBalance_args(...param),
			"getTotalCoinBalance",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCoinPurchaseHistory(
		...param: Parameters<typeof LINEStruct.getCoinPurchaseHistory_args>
	): Promise<LINETypes.getCoinPurchaseHistory_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCoinPurchaseHistory_args(...param),
			"getCoinPurchaseHistory",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCoinProducts(
		...param: Parameters<typeof LINEStruct.getCoinProducts_args>
	): Promise<LINETypes.getCoinProducts_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCoinProducts_args(...param),
			"getCoinProducts",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async reserveCoinPurchase(
		...param: Parameters<typeof LINEStruct.reserveCoinPurchase_args>
	): Promise<LINETypes.reserveCoinPurchase_result["success"]> {
		return await this.client.request.request(
			LINEStruct.reserveCoinPurchase_args(...param),
			"reserveCoinPurchase",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCoinUseAndRefundHistory(
		...param: Parameters<typeof LINEStruct.getCoinUseAndRefundHistory_args>
	): Promise<LINETypes.getCoinUseAndRefundHistory_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCoinUseAndRefundHistory_args(...param),
			"getCoinUseAndRefundHistory",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
