// Generated by scripts/chrline/gen_services.ts from CHRLINE-Patch's
// ChatAppService.  Manual edits are fine — re-running the generator only
// touches services whose CHRLINE-Patch counterpart has changed.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class ChatAppService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/CAPP1";
	errorName = "ChatAppServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getChatapp(
		...param: Parameters<typeof LINEStruct.getChatapp_args>
	): Promise<LINETypes.getChatapp_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getChatapp_args(...param),
			"getChatapp",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getMyChatapps(
		...param: Parameters<typeof LINEStruct.getMyChatapps_args>
	): Promise<LINETypes.getMyChatapps_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getMyChatapps_args(...param),
			"getMyChatapps",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
