// Generated by scripts/services/gen_services.ts from
// scripts/services/endpoints.json.  Edit the manifest (and re-run the
// generator) to change the wrapped method list.  Hand edits to this
// file are preserved as long as the corresponding entry stays in the
// hand-written SKIP_LIST.
import { type BaseClient } from "../../core/mod.ts";
import type { ProtocolKey } from "../../thrift/mod.ts";
import type { BaseService } from "../types.ts";
import { LINEStruct } from "../../thrift/mod.ts";
import type * as LINETypes from "@evex/linejs-types";

export class ShopService implements BaseService {
	client: BaseClient;
	protocolType: ProtocolKey = 4;
	requestPath = "/TSHOP4";
	errorName = "ShopServiceError";
	constructor(client: BaseClient) {
		this.client = client;
	}

	async getProductsByAuthor(
		...param: Parameters<typeof LINEStruct.getProductsByAuthor_args>
	): Promise<LINETypes.getProductsByAuthor_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getProductsByAuthor_args(...param),
			"getProductsByAuthor",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getStudentInformation(
		...param: Parameters<typeof LINEStruct.getStudentInformation_args>
	): Promise<LINETypes.getStudentInformation_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getStudentInformation_args(...param),
			"getStudentInformation",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async canReceivePresent(
		...param: Parameters<typeof LINEStruct.canReceivePresent_args>
	): Promise<void> {
		return await this.client.request.request(
			LINEStruct.canReceivePresent_args(...param),
			"canReceivePresent",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getOwnedProductSummaries(
		...param: Parameters<typeof LINEStruct.getOwnedProductSummaries_args>
	): Promise<LINETypes.getOwnedProductSummaries_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getOwnedProductSummaries_args(...param),
			"getOwnedProductSummaries",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getProductV2(
		...param: Parameters<typeof LINEStruct.getProductV2_args>
	): Promise<LINETypes.getProductV2_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getProductV2_args(...param),
			"getProductV2",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getProductByVersion(
		...param: Parameters<typeof LINEStruct.getProductByVersion_args>
	): Promise<LINETypes.getProductByVersion_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getProductByVersion_args(...param),
			"getProductByVersion",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async placePurchaseOrderForFreeProduct(
		...param: Parameters<
			typeof LINEStruct.placePurchaseOrderForFreeProduct_args
		>
	): Promise<LINETypes.placePurchaseOrderForFreeProduct_result["success"]> {
		return await this.client.request.request(
			LINEStruct.placePurchaseOrderForFreeProduct_args(...param),
			"placePurchaseOrderForFreeProduct",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async placePurchaseOrderWithLineCoin(
		...param: Parameters<typeof LINEStruct.placePurchaseOrderWithLineCoin_args>
	): Promise<LINETypes.placePurchaseOrderWithLineCoin_result["success"]> {
		return await this.client.request.request(
			LINEStruct.placePurchaseOrderWithLineCoin_args(...param),
			"placePurchaseOrderWithLineCoin",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getPurchasedProducts(
		...param: Parameters<typeof LINEStruct.getPurchasedProducts_args>
	): Promise<LINETypes.getPurchasedProducts_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getPurchasedProducts_args(...param),
			"getPurchasedProducts",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getReceivedPresents(
		...param: Parameters<typeof LINEStruct.getReceivedPresents_args>
	): Promise<LINETypes.getReceivedPresents_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getReceivedPresents_args(...param),
			"getReceivedPresents",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getSentPresents(
		...param: Parameters<typeof LINEStruct.getSentPresents_args>
	): Promise<LINETypes.getSentPresents_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getSentPresents_args(...param),
			"getSentPresents",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async notifyProductEvent(
		...param: Parameters<typeof LINEStruct.notifyProductEvent_args>
	): Promise<void> {
		return await this.client.request.request(
			LINEStruct.notifyProductEvent_args(...param),
			"notifyProductEvent",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getProductValidationScheme(
		...param: Parameters<typeof LINEStruct.getProductValidationScheme_args>
	): Promise<LINETypes.getProductValidationScheme_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getProductValidationScheme_args(...param),
			"getProductValidationScheme",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async validateProduct(
		...param: Parameters<typeof LINEStruct.validateProduct_args>
	): Promise<LINETypes.validateProduct_result["success"]> {
		return await this.client.request.request(
			LINEStruct.validateProduct_args(...param),
			"validateProduct",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getRecommendationList(
		...param: Parameters<typeof LINEStruct.getRecommendationList_args>
	): Promise<LINETypes.getRecommendationList_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getRecommendationList_args(...param),
			"getRecommendationList",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getResourceFile(
		...param: Parameters<typeof LINEStruct.getResourceFile_args>
	): Promise<LINETypes.getResourceFile_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getResourceFile_args(...param),
			"getResourceFile",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getAutoSuggestionShowcase(
		...param: Parameters<typeof LINEStruct.getAutoSuggestionShowcase_args>
	): Promise<LINETypes.getAutoSuggestionShowcase_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getAutoSuggestionShowcase_args(...param),
			"getAutoSuggestionShowcase",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getSubscriptionStatus(
		...param: Parameters<typeof LINEStruct.getSubscriptionStatus_args>
	): Promise<LINETypes.getSubscriptionStatus_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getSubscriptionStatus_args(...param),
			"getSubscriptionStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getSuggestResourcesV2(
		...param: Parameters<typeof LINEStruct.getSuggestResourcesV2_args>
	): Promise<LINETypes.getSuggestResourcesV2_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getSuggestResourcesV2_args(...param),
			"getSuggestResourcesV2",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async reserveCoinPurchase(
		...param: Parameters<typeof LINEStruct.reserveCoinPurchase_args>
	): Promise<LINETypes.reserveCoinPurchase_result["success"]> {
		return await this.client.request.request(
			LINEStruct.reserveCoinPurchase_args(...param),
			"reserveCoinPurchase",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCoinUseAndRefundHistory(
		...param: Parameters<typeof LINEStruct.getCoinUseAndRefundHistory_args>
	): Promise<LINETypes.getCoinUseAndRefundHistory_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCoinUseAndRefundHistory_args(...param),
			"getCoinUseAndRefundHistory",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCoinProducts(
		...param: Parameters<typeof LINEStruct.getCoinProducts_args>
	): Promise<LINETypes.getCoinProducts_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCoinProducts_args(...param),
			"getCoinProducts",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getCoinPurchaseHistory(
		...param: Parameters<typeof LINEStruct.getCoinPurchaseHistory_args>
	): Promise<LINETypes.getCoinPurchaseHistory_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getCoinPurchaseHistory_args(...param),
			"getCoinPurchaseHistory",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async createCombinationSticker(
		...param: Parameters<typeof LINEStruct.createCombinationSticker_args>
	): Promise<LINETypes.createCombinationSticker_result["success"]> {
		return await this.client.request.request(
			LINEStruct.createCombinationSticker_args(...param),
			"createCombinationSticker",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async shouldShowWelcomeStickerBanner(
		...param: Parameters<typeof LINEStruct.shouldShowWelcomeStickerBanner_args>
	): Promise<LINETypes.shouldShowWelcomeStickerBanner_result["success"]> {
		return await this.client.request.request(
			LINEStruct.shouldShowWelcomeStickerBanner_args(...param),
			"shouldShowWelcomeStickerBanner",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async stopBundleSubscription(
		...param: Parameters<typeof LINEStruct.stopBundleSubscription_args>
	): Promise<LINETypes.stopBundleSubscription_result["success"]> {
		return await this.client.request.request(
			LINEStruct.stopBundleSubscription_args(...param),
			"stopBundleSubscription",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getProductLatestVersionForUser(
		...param: Parameters<typeof LINEStruct.getProductLatestVersionForUser_args>
	): Promise<LINETypes.getProductLatestVersionForUser_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getProductLatestVersionForUser_args(...param),
			"getProductLatestVersionForUser",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async getMusicSubscriptionStatus(
		...param: Parameters<typeof LINEStruct.getMusicSubscriptionStatus_args>
	): Promise<LINETypes.getMusicSubscriptionStatus_result["success"]> {
		return await this.client.request.request(
			LINEStruct.getMusicSubscriptionStatus_args(...param),
			"getMusicSubscriptionStatus",
			this.protocolType,
			true,
			this.requestPath,
		);
	}

	async addThemeToSubscriptionSlot(
		...param: Parameters<typeof LINEStruct.addThemeToSubscriptionSlot_args>
	): Promise<LINETypes.addThemeToSubscriptionSlot_result["success"]> {
		return await this.client.request.request(
			LINEStruct.addThemeToSubscriptionSlot_args(...param),
			"addThemeToSubscriptionSlot",
			this.protocolType,
			true,
			this.requestPath,
		);
	}
}
